<?php

return [
    'proximity' => [
        'name' => 'f5/ranges.proximity',
        'desc' => 'f5/areaofeffect.proximity_target',
        'range' => false,
        'types' => ['saving_throw'],
        'limited_targets' => false,
        'target_type' => 'aoe',
        'targets_at_30' => 2,
    ],
    'melee' => [
        'name' => 'f5/ranges.melee',
        'desc' => 'f5/areaofeffect.melee_target',
        'range' => false,
        'types' => ['attack'],
        'limited_targets' => true,
        'target_type' => 'select',
        'targets_at_30' => 1,
    ],
    'touch' => [
        'name' => 'f5/ranges.touch',
        'desc' => 'f5/areaofeffect.touch_target',
        'range' => false,
        'types' => ['saving_throw'],
        'limited_targets' => true,
        'target_type' => 'select',
        'targets_at_30' => 1,
    ],
    'ranged' => [
        'name' => 'f5/ranges.ranged',
        'desc' => 'f5/areaofeffect.ranged_target',
        'range' => true,
        'types' => ['attack'],
        'limited_targets' => true,
        'target_type' => 'select',
        'targets_at_30' => 1,
    ],
    'melee_or_ranged' => [
        'name' => 'f5/ranges.melee_or_ranged',
        //'desc' => 'f5/areaofeffect.melee_or_ranged_target',
        'range' => true,
        'types' => ['attack'],
        'limited_targets' => true,
        'target_type' => 'select',
        'targets_at_30' => 1,
    ],
    'line' => [
        'name' => 'f5/ranges.line',
        'desc' => 'f5/areaofeffect.line_target',
        'range' => false,
        'types' => ['saving_throw'],
        'limited_targets' => false,
        'target_type' => 'aoe',
        'targets_at_30' => 1.5,
    ],
    'cone' => [
        'name' => 'f5/ranges.cone',
        'desc' => 'f5/areaofeffect.cone_target',
        'range' => false,
        'types' => ['saving_throw'],
        'limited_targets' => false,
        'target_type' => 'aoe',
        'targets_at_30' => 2,
    ],
    'cube' => [
        'name' => 'f5/ranges.cube',
        'desc' => 'f5/areaofeffect.cube_target',
        'range' => true,
        'types' => ['saving_throw'],
        'limited_targets' => true,
        'target_type' => 'aoe',
        'targets_at_30' => 2.5,
    ],
    'sphere' => [
        'name' => 'f5/ranges.sphere',
        'desc' => 'f5/areaofeffect.sphere_target',
        'range' => true,
        'types' => ['saving_throw'],
        'limited_targets' => true,
        'target_type' => 'aoe',
        'targets_at_30' => 3,
    ],
];