<?php

return [
    'blinded' => [
        'name' => 'f5/conditions.blinded',
        'past_tense' => 'f5/conditions.blinded',
        'is' => 'f5/conditions.condition_desc_becomes',
        'not' => 'f5/conditions.condition_desc_not',
        'rank' => 3,
        'has_duration' => true,
    ],
    'charmed' => [
        'name' => 'f5/conditions.charmed',
        'past_tense' => 'f5/conditions.charmed',
        'is' => 'f5/conditions.condition_desc_becomes',
        'not' => 'f5/conditions.condition_desc_not',
        'rank' => 2,
        'has_duration' => true,
    ],
    'deafened' => [
        'name' => 'f5/conditions.deafened',
        'past_tense' => 'f5/conditions.deafened',
        'is' => 'f5/conditions.condition_desc_becomes',
        'not' => 'f5/conditions.condition_desc_not',
        'rank' => 1,
        'has_duration' => true,
    ],
    'exhaustion' => [
        'name' => 'f5/conditions.exhaustion',
        'past_tense' => 'f5/conditions.exhausted',
        'is' => 'f5/conditions.condition_desc_gains_point',
        'not' => 'f5/conditions.condition_desc_not_gains_point',
        'rank' => 3,
        'has_duration' => false,
    ],
    'frightened' => [
        'name' => 'f5/conditions.frightened',
        'past_tense' => 'f5/conditions.frightened',
        'is' => 'f5/conditions.condition_desc_becomes',
        'not' => 'f5/conditions.condition_desc_not',
        'rank' => 2,
        'has_duration' => true,
    ],
    'grappled' => [
        'name' => 'f5/conditions.grappled',
        'past_tense' => 'f5/conditions.grappled',
        'is' => 'f5/conditions.condition_desc_becomes',
        'not' => 'f5/conditions.condition_desc_not',
        'rank' => 2,
        'has_duration' => false,
    ],
    'incapacitated' => [
        'name' => 'f5/conditions.incapacitated',
        'past_tense' => 'f5/conditions.incapacitated',
        'is' => 'f5/conditions.condition_desc_becomes',
        'not' => 'f5/conditions.condition_desc_not',
        'rank' => 3,
        'has_duration' => true,
    ],
    'paralyzed' => [
        'name' => 'f5/conditions.paralyzed',
        'past_tense' => 'f5/conditions.paralyzed',
        'is' => 'f5/conditions.condition_desc_becomes',
        'not' => 'f5/conditions.condition_desc_not',
        'rank' => 4,
        'has_duration' => true,
    ],
    'petrified' => [
        'name' => 'f5/conditions.petrified',
        'past_tense' => 'f5/conditions.petrified',
        'is' => 'f5/conditions.condition_desc_becomes',
        'not' => 'f5/conditions.condition_desc_not',
        'rank' => 5,
        'has_duration' => true,
    ],
    'poisoned' => [
        'name' => 'f5/conditions.poisoned',
        'past_tense' => 'f5/conditions.poisoned',
        'is' => 'f5/conditions.condition_desc_becomes',
        'not' => 'f5/conditions.condition_desc_not',
        'rank' => 2,
        'has_duration' => true,
    ],
    'prone' => [
        'name' => 'f5/conditions.prone',
        'past_tense' => 'f5/conditions.condition_desc_knocked',
        'is' => 'f5/conditions.condition_desc_is_knocked',
        'each' => 'f5/conditions.condition_desc_is_knocked',
        'not' => 'f5/conditions.condition_desc_is_not_knocked',
        'rank' => 1.5,
        'has_duration' => false,
    ],
    'restrained' => [
        'name' => 'f5/conditions.restrained',
        'past_tense' => 'f5/conditions.restrained',
        'is' => 'f5/conditions.condition_desc_becomes',
        'not' => 'f5/conditions.condition_desc_not',
        'rank' => 3,
        'has_duration' => true,
    ],
    'stunned' => [
        'name' => 'f5/conditions.stunned',
        'past_tense' => 'f5/conditions.stunned',
        'is' => 'f5/conditions.condition_desc_becomes',
        'not' => 'f5/conditions.condition_desc_not',
        'rank' => 3.5,
        'has_duration' => true,
    ],
    'unconsious' => [
        'name' => 'f5/conditions.unconsious',
        'past_tense' => 'f5/conditions.condition_desc_knocked',
        'is' => 'f5/conditions.condition_desc_becomes',
        'not' => 'f5/conditions.condition_desc_not',
        'rank' => 4.5,
        'has_duration' => true,
    ],
    'swallowed' => [
        'name' => 'f5/conditions.swallowed',
        'past_tense' => 'f5/conditions.swallowed',
        'is' => 'f5/conditions.condition_desc_is',
        'not' => 'f5/conditions.condition_desc_not',
        'description' => 'f5/conditions.swallowed_description',
        'rank' => 4,
        'has_duration' => false,
    ],
    'on_fire' => [
        'name' => 'f5/conditions.on_fire',
        'past_tense' => 'f5/conditions.on_fire',
        'is' => 'f5/conditions.is_on_fire',
        'not' => 'f5/conditions.not_on_fire',
        'description' => 'f5/conditions.on_fire_description',
        'rank' => 3,
        'has_duration' => false,
    ],
    'pushed' => [
        'name' => 'f5/conditions.pushed',
        'past_tense' => 'f5/conditions.pushed',
        'is' => 'f5/conditions.condition_desc_is_pushed',
        'not' => 'f5/conditions.condition_desc_is_not_pushed',
        'distance' => [1,2,3,4,5,6],
        'rank' => 1,
        'has_duration' => false,
    ],
    'surprised' => [
        'name' => 'f5/conditions.surprised',
        'past_tense' => 'f5/conditions.surprised',
        'is' => 'f5/conditions.condition_desc_becomes',
        'not' => 'f5/conditions.condition_desc_not',
        'rank' => 1,
        'has_duration' => false,
    ],


];