<?php

$con = 2;
$hitdice = 8;

return [
    1 => [
        'average_dpr' => 9,
        'average_hp' => ((1 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 4,
        'proficiency' => 2,
        'xp_thresholds' => [
            'easy' => 25,
            'medium' => 50,
            'hard' => 75,
            'deadly' => 100,
        ],
    ],
    2 => [
        'average_dpr' => 12, 
        'average_hp' => ((2 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 4,
        'proficiency' => 2,
        'xp_thresholds' => [
            'easy' => 50,
            'medium' => 100,
            'hard' => 150,
            'deadly' => 200,
        ],
    ],
    3 => [
        'average_dpr' => 14, 
        'average_hp' => ((3 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 4,
        'proficiency' => 2,
        'xp_thresholds' => [
            'easy' => 75,
            'medium' => 150,
            'hard' => 225,
            'deadly' => 400,
        ],
    ],
    4 => [
        'average_dpr' => 18, 
        'average_hp' => ((4 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 5,
        'proficiency' => 2,
        'xp_thresholds' => [
            'easy' => 125,
            'medium' => 250,
            'hard' => 375,
            'deadly' => 500,
        ],
    ],
    5 => [
        'average_dpr' => 31, 
        'average_hp' => ((5 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 5,
        'proficiency' => 3,
        'xp_thresholds' => [
            'easy' => 250,
            'medium' => 500,
            'hard' => 750,
            'deadly' => 1100,
        ],
    ],
    6 => [
        'average_dpr' => 32, 
        'average_hp' => ((6 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 5,
        'proficiency' => 3,
        'xp_thresholds' => [
            'easy' => 300,
            'medium' => 600,
            'hard' => 900,
            'deadly' => 1400,
        ],
    ],
    7 => [
        'average_dpr' => 33, 
        'average_hp' => ((7 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 5,
        'proficiency' => 3,
        'xp_thresholds' => [
            'easy' => 350,
            'medium' => 750,
            'hard' => 1100,
            'deadly' => 1700,
        ],
    ],
    8 => [
        'average_dpr' => 37, 
        'average_hp' => ((8 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 5,
        'proficiency' => 3,
        'xp_thresholds' => [
            'easy' => 450,
            'medium' => 900,
            'hard' => 1400,
            'deadly' => 2100,
        ],
    ],
    9 => [
        'average_dpr' => 39, 
        'average_hp' => ((9 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 5,
        'proficiency' => 4,
        'xp_thresholds' => [
            'easy' => 550,
            'medium' => 1100,
            'hard' => 1600,
            'deadly' => 2400,
        ],
    ],
    10 => [
        'average_dpr' => 40, 
        'average_hp' => ((10 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 5,
        'proficiency' => 4,
        'xp_thresholds' => [
            'easy' => 600,
            'medium' => 1200,
            'hard' => 1900,
            'deadly' => 2800,
        ],
    ],
    11 => [
        'average_dpr' => 46, 
        'average_hp' => ((11 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 5,
        'proficiency' => 4,
        'xp_thresholds' => [
            'easy' => 800,
            'medium' => 1600,
            'hard' => 2400,
            'deadly' => 3600,
        ],
    ],
    12 => [
        'average_dpr' => 48, 
        'average_hp' => ((12 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 5,
        'proficiency' => 4,
        'xp_thresholds' => [
            'easy' => 1000,
            'medium' => 2000,
            'hard' => 3000,
            'deadly' => 4500,
        ],
    ],
    13 => [
        'average_dpr' => 50, 
        'average_hp' => ((13 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 5,
        'proficiency' => 5,
        'xp_thresholds' => [
            'easy' => 1100,
            'medium' => 2200,
            'hard' => 3400,
            'deadly' => 5100,
        ],
    ],
    14 => [
        'average_dpr' => 51, 
        'average_hp' => ((14 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 5,
        'proficiency' => 5,
        'xp_thresholds' => [
            'easy' => 1250,
            'medium' => 2500,
            'hard' => 3800,
            'deadly' => 5700,
        ],
    ],
    15 => [
        'average_dpr' => 53, 
        'average_hp' => ((15 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 5,
        'proficiency' => 5,
        'xp_thresholds' => [
            'easy' => 1400,
            'medium' => 2800,
            'hard' => 4300,
            'deadly' => 6400,
        ],
    ],
    16 => [
        'average_dpr' => 55, 
        'average_hp' => ((16 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 5,
        'proficiency' => 5,
        'xp_thresholds' => [
            'easy' => 1600,
            'medium' => 3200,
            'hard' => 4800,
            'deadly' => 7200,
        ],
    ],
    17 => [
        'average_dpr' => 70, 
        'average_hp' => ((17 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 5,
        'proficiency' => 6,
        'xp_thresholds' => [
            'easy' => 2000,
            'medium' => 3900,
            'hard' => 5900,
            'deadly' => 8800,
        ],
    ],
    18 => [
        'average_dpr' => 72, 
        'average_hp' => ((18 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 5,
        'proficiency' => 6,
        'xp_thresholds' => [
            'easy' => 2100,
            'medium' => 4200,
            'hard' => 6300,
            'deadly' => 9500,
        ],
    ],
    19 => [
        'average_dpr' => 74, 
        'average_hp' => ((19 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 5,
        'proficiency' => 6,
        'xp_thresholds' => [
            'easy' => 2400,
            'medium' => 4900,
            'hard' => 7300,
            'deadly' => 10900,
        ],
    ],
    20 => [
        'average_dpr' => 79, 
        'average_hp' => ((20 - 1) * (($hitdice/2+1) + $con)) + $hitdice + $con,
        'average_modifier' => 6,
        'proficiency' => 6,
        'xp_thresholds' => [
            'easy' => 2800,
            'medium' => 5700,
            'hard' => 8500,
            'deadly' => 12700,
        ],
    ],
];